# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Heesu Kim
description:      My personal website showcasing projects in software engineering, AI, finance, medical data, video games, and thoughts on tech.
url:              https://kheesu.github.io
#baseurl:          /

paginate:         5

# Custom vars
version:          2.1.0

