title: Heesu Kim | Portfolio & Blog
description: My personal website showcasing projects in software engineering, AI, finance, medical data, video games, and thoughts on tech.
remote_theme: poole/hyde